"""Compose the temporary domain bridge with one scheduler adapter."""
from __future__ import annotations

import shlex
from pathlib import Path

from ..scheduling.hepjob import HEPJobConfig, HEPJobScheduler
from ..scheduling.local import LocalScheduler
from ..scheduling.supervisor import JobSupervisor
from ..world import forwarded_payload_env
from .backend import WorkerBackend


def build_backend(ctx) -> WorkerBackend:
    name = str(ctx.cfg.get("execution_backend") or "local").strip().lower()
    if name == "local":
        scheduler = LocalScheduler()
        poll_seconds = 0.2
    elif name == "hepjob":
        raw = ctx.cfg.get("hepjob") or {}
        scheduler = HEPJobScheduler(HEPJobConfig(
            schedd_name=str(raw["schedd_name"]),
            collector=(str(raw["collector"]) if raw.get("collector") else None),
            accounting_group=str(raw["accounting_group"]),
            accounting_group_user=str(raw["accounting_group_user"]),
            request_os=str(raw.get("request_os") or "AlmaLinux9"),
            ihep_group=(str(raw["ihep_group"]) if raw.get("ihep_group") else None),
            submit_cmd=str(raw.get("submit_cmd") or HEPJobConfig.submit_cmd),
            query_cmd=str(raw.get("query_cmd") or HEPJobConfig.query_cmd),
            remove_cmd=str(raw.get("remove_cmd") or HEPJobConfig.remove_cmd),
            environment_script=_write_job_environment(Path(ctx.run_dir)),
        ))
        poll_seconds = float(raw.get("poll_seconds", 30))
    else:
        raise ValueError(
            f"execution.backend: unknown backend {name!r} "
            "(expected local|hepjob)"
        )
    return WorkerBackend(
        ctx,
        scheduler=scheduler,
        supervisor=JobSupervisor(
            workspace_provider=ctx.workspace,
            poll_seconds=poll_seconds,
        ),
    )


def _write_job_environment(run_dir: Path) -> Path:
    path = run_dir / "job_env.sh"
    package_root = Path(__file__).resolve().parents[2]
    lines = ["# generated by SimpleLoop scheduling composition"]
    for key, value in sorted(forwarded_payload_env().items()):
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.append(
        f"export PYTHONPATH={shlex.quote(str(package_root))}"
        '"${PYTHONPATH:+:$PYTHONPATH}"'
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(0o600)
    return path


__all__ = ["WorkerBackend", "build_backend"]
